import logfire
from apps.config import settings
from apps.agents.state import AgentState
from langchain_groq import ChatGroq


grader_llm = ChatGroq(
    api_key=settings.GROK_API_KEY,
    model=settings.GROQ_model,
    temperature=settings.TEMPRATURE
)


def grader_node(state: AgentState) -> AgentState:
    """
    Evaluates the final answer generated by the responder node.

    Uses the `final_ans` from the state and prompts the LLM to assess its
    correctness, relevance, and completeness. Updates the state with
    `grader_approved` ("APPROVED"/"REJECTED") and `retrieval_attempts`.
    Skips grading entirely for conversational queries.
    """
    if state.get("current_query") == "CONVERSATIONAL":
        return {
            "grader_approved": "APPROVED",
            "retrieval_attempts": 0,
            "status": "Conversational answer — grading skipped."
        }

    final_ans = state.get("final_ans", "")
    documents = state.get("documents", [])
    current_query = state.get("current_query", "")

    # Fix 1: Format documents into clean plain text for the grader LLM
    if documents:
        formatted_docs = "\n\n".join(
            f"[Doc {i+1}]: {doc.page_content}" if hasattr(doc, "page_content") else f"[Doc {i+1}]: {str(doc)}"
            for i, doc in enumerate(documents)
        )
    else:
        formatted_docs = "No documents retrieved."

    if not final_ans:
        logfire.warning("Grader received empty final_ans — defaulting to REJECTED")
        return {
            "grader_approved": "REJECTED",
            "retrieval_attempts": state.get("retrieval_attempts", 0) + 1,
            "status": "No answer was generated to grade.",
        }

    # Fix 3: Guard against empty documents
    if not documents:
        logfire.warning("Grader received no documents — defaulting to REJECTED")
        return {
            "grader_approved": "REJECTED",
            "retrieval_attempts": state.get("retrieval_attempts", 0) + 1,
            "status": "No documents retrieved to grade against.",
        }

    # Fix 2: Query-aware, relaxed grader prompt
    prompt = f"""
    You are a technical evaluator for a RAG (Retrieval-Augmented Generation) pipeline.
    Your job is to judge whether the FINAL ANSWER correctly addresses the USER QUERY
    based on the FETCHED DOCUMENTS.

    USER QUERY:
    "{current_query}"

    FETCHED DOCUMENTS / CONTEXT:
    \"\"\"
    {formatted_docs}
    \"\"\"

    FINAL ANSWER:
    "{final_ans}"

    QUERY TYPE DETECTION:
    - If the query starts with "what is", "define", "explain", "what are" → it is a DEFINITIONAL query.
    - If the query describes a problem, error, failure, or asks "how to fix/configure/debug" → it is a TECHNICAL query.

    Evaluation Criteria:

    1. RELEVANCE: Do the fetched documents relate to the topic in the USER QUERY?
       → Fail ONLY if documents are completely off-topic (e.g., query about pods but docs are about recipes).
       → Pass if docs partially cover the topic.

    2. COMPLETENESS:
       → For DEFINITIONAL queries: PASS if the answer gives a correct basic definition. A short answer is acceptable.
       → For TECHNICAL queries: PASS if the answer addresses the key steps or solution. Partial coverage is acceptable.
       → Fail ONLY if the answer is completely empty, nonsensical, or says "I don't know".

    3. GROUNDEDNESS: Is the answer reasonably based on the documents?
       → Fail ONLY if the answer directly contradicts the documents or introduces completely fabricated facts.
       → Minor LLM elaboration is acceptable as long as it does not contradict the docs.

    Decision Rules:
    - Output APPROVED if the answer is relevant, reasonable, and not contradicting the docs.
    - Output REJECTED only if the answer is clearly wrong, off-topic, or contradicts the documents.
    - Output ONLY the single word: APPROVED or REJECTED.
    - Do NOT include explanations, punctuation, or any other text.
    """

    with logfire.span("🧑‍⚖️ Grader Evaluation"):
        raw = grader_llm.invoke(prompt).content.strip().upper()  # normalize case

        # Fallback for unexpected LLM output
        if raw not in ("APPROVED", "REJECTED"):
            logfire.warning(f"Unexpected grader output: '{raw}' — defaulting to REJECTED")
            grader_decision = "REJECTED"
        else:
            grader_decision = raw

        logfire.info(f"Grader decision: {grader_decision}")

    if grader_decision == "APPROVED":
        current_attempts = state.get("retrieval_attempts", 0)
        status = "Answer approved by grader."
        enhanced_query = current_query  # No change to query if approved
    else:
        current_attempts = state.get("retrieval_attempts", 0) + 1 
        status = f"Answer rejected. Documents were irrelevant or insufficient (Attempt {current_attempts})."
        enhance_prompt = f"""
        ORIGINAL QUERY: "{current_query}"
        PREVIOUS FAILED ANSWER: "{final_ans}"
        ATTEMPT NUMBER: {current_attempts}
        Reformulate the search query to approach from a different angle...
        """
        enhanced_query = grader_llm.invoke(enhance_prompt).content.strip()

    return {
        "current_query": enhanced_query,
        "grader_approved": grader_decision,
        "retrieval_attempts": current_attempts,
        "status": status,
    }