import logfire
from apps.config import settings
from apps.agents.state import AgentState
from langchain_groq import ChatGroq


grader_llm = ChatGroq(
    api_key=settings.GROK_API_KEY,
    model=settings.GROQ_model,
    temperature=settings.TEMPRATURE
)


def grader_node(state: AgentState) -> AgentState:
    """
    Evaluates the final answer generated by the responder node.

    Uses the `final_ans` from the state and prompts the LLM to assess its
    correctness, relevance, and completeness. Updates the state with
    `grader_approved` ("APPROVED"/"REJECTED") and `retrieval_attempts`.
    Skips grading entirely for conversational queries.
    """
    if state.get("current_query") == "CONVERSATIONAL":
        return {
            "grader_approved": "APPROVED",
            "retrieval_attempts": 0,
            "status": "Conversational answer — grading skipped."
        }

    final_ans = state.get("final_ans", "")
    documents = state.get("documents", [])
    current_query = state.get("current_query", "")

    if not final_ans:
        logfire.warning("Grader received empty final_ans — defaulting to REJECTED")
        return {
            "grader_approved": "REJECTED",
            "retrieval_attempts": state.get("retrieval_attempts", 0) + 1,
            "status": "No answer was generated to grade.",
        }

    prompt = f"""
    You are a strict technical evaluator for a RAG (Retrieval-Augmented Generation) pipeline.
    Your sole job is to judge whether the retrieved documents were relevant AND whether
    the final answer is accurate, complete, and grounded in those documents.

    USER QUERY:
    "{current_query}"

    FETCHED DOCUMENTS / CONTEXT:
    \"\"\"
    {documents}
    \"\"\"

    FINAL ANSWER:
    "{final_ans}"

    Evaluation Criteria — ALL must pass for APPROVED:

    1. RELEVANCE: Do the fetched documents directly address the technical domain
       or specific problem stated in the USER QUERY?
       → Fail if documents are off-topic, generic, or unrelated.

    2. COMPLETENESS: Does the FINAL ANSWER address the USER QUERY fully,
       covering key technical details without leaving critical gaps?
       → Fail if the answer is vague, partial, or deflects the question.

    3. GROUNDEDNESS: Is every claim in the FINAL ANSWER traceable to the
       FETCHED DOCUMENTS? The answer must not introduce facts, APIs, methods,
       or figures that are absent from the documents.
       → Fail if the answer hallucinates or contradicts the documents.

    Decision Rules:
    - Output APPROVED only if ALL three criteria pass.
    - Output REJECTED if ANY one criterion fails.
    - Output ONLY the single word: APPROVED or REJECTED.
    - Do NOT include explanations, punctuation, or any other text.
    """

    with logfire.span("🧑‍⚖️ Grader Evaluation"):
        raw = grader_llm.invoke(prompt).content.strip().upper()  # normalize case

        # Fallback for unexpected LLM output
        if raw not in ("APPROVED", "REJECTED"):
            logfire.warning(f"Unexpected grader output: '{raw}' — defaulting to REJECTED")
            grader_decision = "REJECTED"
        else:
            grader_decision = raw

        logfire.info(f"Grader decision: {grader_decision}")

    if grader_decision == "APPROVED":
        current_attempts = state.get("retrieval_attempts", 0)
        status = "Answer approved by grader."
        enhanced_query = current_query  # No change to query if approved
    else:
        current_attempts = state.get("retrieval_attempts", 0) + 1 
        status = f"Answer rejected. Documents were irrelevant or insufficient (Attempt {current_attempts})."
        enhance_prompt = f"""
        ORIGINAL QUERY: "{current_query}"
        PREVIOUS FAILED ANSWER: "{final_ans}"
        ATTEMPT NUMBER: {current_attempts}
        Reformulate the search query to approach from a different angle...
        """
        enhanced_query = grader_llm.invoke(enhance_prompt).content.strip()

    return {
        "current_query": enhanced_query,
        "grader_approved": grader_decision,
        "retrieval_attempts": current_attempts,
        "status": status,
    }